print("########################")
print("#   How to Train Your  #")
print("#        DRAGON        #")
print("########################")
print("")

print("Staring: ")
print("Hiccup")
print("Toothless")
print("Astrid")
print("Stormfly")
print("Snotlout")
print("Hookfang")
print("Fishlegs")
print("Meatlug")
print("Roughnut")
print("Toughnut")
print("Barf and Belch")